-- MySQL Script generated by MySQL Workbench
-- Sat Apr 11 16:25:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema` DEFAULT CHARACTER SET utf8 ;
USE `sistema` ;

-- -----------------------------------------------------
-- Table `sistema`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`estado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`cidade` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `idEstado` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado1_idx` (`idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `sistema`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5565
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`colaborador` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `celular` VARCHAR(11) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `admin` VARCHAR(4) NOT NULL,
  `ativo` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`despesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`despesa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `valor` FLOAT NULL DEFAULT NULL,
  `ativo` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`filial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`filial` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(14) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(15) NOT NULL,
  `complemento` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(10) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `ativo` VARCHAR(4) NOT NULL,
  `idCidade` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_filial_cidade1_idx` (`idCidade` ASC) VISIBLE,
  CONSTRAINT `fk_filial_cidade1`
    FOREIGN KEY (`idCidade`)
    REFERENCES `sistema`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`viagem` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `localPartida` TEXT NOT NULL,
  `dataInicio` DATETIME NOT NULL,
  `dataTermino` DATETIME NULL DEFAULT NULL,
  `descricao` TEXT NOT NULL,
  `custoTotal` FLOAT NULL DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL,
  `idColaborador` INT(11) NOT NULL,
  `idFilial` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_viagem_colaborador1_idx` (`idColaborador` ASC) VISIBLE,
  INDEX `fk_viagem_filial1_idx` (`idFilial` ASC) VISIBLE,
  CONSTRAINT `fk_viagem_colaborador1`
    FOREIGN KEY (`idColaborador`)
    REFERENCES `sistema`.`colaborador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_filial1`
    FOREIGN KEY (`idFilial`)
    REFERENCES `sistema`.`filial` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`parada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`parada` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `destino` TEXT NOT NULL,
  `motivo` TEXT NOT NULL,
  `dataInicio` DATETIME NOT NULL,
  `dataTermino` DATETIME NOT NULL,
  `idViagem` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parada_viagem1_idx` (`idViagem` ASC) VISIBLE,
  CONSTRAINT `fk_parada_viagem1`
    FOREIGN KEY (`idViagem`)
    REFERENCES `sistema`.`viagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`despesa_parada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`despesa_parada` (
  `idDespesa` INT(11) NOT NULL,
  `idParada` INT(11) NOT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quantidade` INT(11) NOT NULL,
  `valor` FLOAT NOT NULL,
  `comprovante` VARCHAR(255) NULL DEFAULT NULL,
  `observacao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_despesa_has_parada_parada1_idx` (`idParada` ASC) VISIBLE,
  INDEX `fk_despesa_has_parada_despesa1_idx` (`idDespesa` ASC) VISIBLE,
  CONSTRAINT `fk_despesa_has_parada_despesa1`
    FOREIGN KEY (`idDespesa`)
    REFERENCES `sistema`.`despesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_despesa_has_parada_parada1`
    FOREIGN KEY (`idParada`)
    REFERENCES `sistema`.`parada` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 371
DEFAULT CHARACTER SET = utf8;

USE `sistema` ;

-- -----------------------------------------------------
-- procedure colaborador_insert
-- -----------------------------------------------------

DELIMITER $$
USE `sistema`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `colaborador_insert`(IN `pid` INT(11), IN `pnome` VARCHAR(100), IN `pcpf` VARCHAR(11), IN `pcelular` VARCHAR(11), IN `pemail` VARCHAR(254), IN `plogin` VARCHAR(45), IN `psenha` VARCHAR(255), IN `padmin` VARCHAR(4), IN `pativo` VARCHAR(4))
BEGIN
	INSERT INTO colaborador (id, nome, cpf, celular, email, login, senha, admin, ativo) VALUES (pid, pnome, pcpf, pcelular, pemail, plogin, psenha, padmin, pativo);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure despesa_insert
-- -----------------------------------------------------

DELIMITER $$
USE `sistema`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `despesa_insert`(IN `pid` INT(11), IN `pdescricao` VARCHAR(255), IN `pvalor` FLOAT, IN `pativo` VARCHAR(4))
BEGIN
	INSERT INTO despesa (id, descricao, valor, ativo) VALUES (pid, pdescricao, pvalor, pativo);
    
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure despesa_parada_insert
-- -----------------------------------------------------

DELIMITER $$
USE `sistema`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `despesa_parada_insert`(
pid INT(11),
piddespesa INT(11),
pidparada INT(11),
pvalor FLOAT,
pcomprovante VARCHAR(255),
pquantidade INT(11),
pdata DATE

)
BEGIN
	INSERT INTO despesa_parada (idDespesa, idParada, id, quantidade, valor, comprovante, data) VALUES (piddespesa, pidparada, pid, pquantidade, pvalor, pcomprovante, pdata);
    
    SELECT * FROM despesa_parada WHERE id = last_insert_id();
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure filial_insert
-- -----------------------------------------------------

DELIMITER $$
USE `sistema`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `filial_insert`(IN `pid` INT(11), IN `pcnpj` VARCHAR(14), IN `pnome` VARCHAR(255), IN `pcep` VARCHAR(10), IN `plogradouro` VARCHAR(100), IN `pbairro` VARCHAR(100), IN `pnumero` VARCHAR(15), IN `pcomplemento` VARCHAR(255), IN `ptelefone` VARCHAR(10), IN `pemail` VARCHAR(254), IN `pativo` VARCHAR(4), IN `pidCidade` INT(11))
BEGIN
	INSERT INTO filial (id, cnpj, nome, cep, logradouro, bairro, numero, complemento, telefone, email, ativo, idCidade ) VALUES (pid, pcnpj, pnome, pcep, plogradouro, pbairro, pnumero, pcomplemento, ptelefone, pemail, pativo, pidcidade);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure parada_insert
-- -----------------------------------------------------

DELIMITER $$
USE `sistema`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `parada_insert`(IN `pid` INT(11), IN `pdestino` TEXT, IN `pmotivo` TEXT, IN `pdataInicio` DATETIME, IN `pdataTermino` DATETIME, IN `pidViagem` INT(11))
BEGIN
	INSERT INTO parada (id, destino, motivo, dataInicio, dataTermino, idViagem) VALUES (pid, pdestino, pmotivo, pdataInicio, pdataTermino, pidViagem);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure viagem_insert
-- -----------------------------------------------------

DELIMITER $$
USE `sistema`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `viagem_insert`(IN `pid` INT(11), IN `plocalPartida` TEXT, IN `pdataInicio` DATETIME, IN `pdataTermino` DATETIME, IN `pdescricao` TEXT, IN `pcustoTotal` FLOAT, IN `pstatus` VARCHAR(20), IN `pidFilial` INT(11), IN `pidColaborador` INT(11))
BEGIN
	INSERT INTO viagem (id, localPartida, dataInicio, dataTermino, descricao, custoTotal, status, idFilial, idColaborador) VALUES (pid, plocalPartida, pdataInicio, pdataTermino, pdescricao, pcustoTotal, pstatus, pidFilial, pidColaborador);

END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
